<template>
    <div>
        <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Curp</th>
                <th>Cargo</th>
                <th>Grupo/Categoría</th>
                <th>Concurso</th>
            </tr>
        </thead>
        <tbody>
            
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </tbody>
    </table>

    </div>
</template>
<script>
</script>